;	NHL 95 graphics95_02. Retail $1A1A1A-$1A6C27 (21006 bytes).
;	ArenaGfxBank (94 graphics94 ArenaGfxBank): the home team graphics LoadHomeTeamGfx loads, $30A bytes per team, read through
;	TeamGfxList (fourway95, TeamList order; ASE and ASW share one). One incbin per team in bank order (extractAssets95.js).

ArenaGfxBank	;retail $1A1A1A-$1A6C27. LoadHomeTeamGfx: one block of $30A bytes per team (TeamGfxList)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxANH.bin	;$1A1A1A, ANH (ArenaGfxBank+$0)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxBUF.bin	;$1A1D24, BUF (ArenaGfxBank+$30A)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxCGY.bin	;$1A202E, CGY (ArenaGfxBank+$614)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxCHI.bin	;$1A2338, CHI (ArenaGfxBank+$91E)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxDAL.bin	;$1A2642, DAL (ArenaGfxBank+$C28)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxDET.bin	;$1A294C, DET (ArenaGfxBank+$F32)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxEDM.bin	;$1A2C56, EDM (ArenaGfxBank+$123C)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxFLA.bin	;$1A2F60, FLA (ArenaGfxBank+$1546)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxHFD.bin	;$1A326A, HFD (ArenaGfxBank+$1850)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxLA.bin	;$1A3574, LA (ArenaGfxBank+$1B5A)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxMTL.bin	;$1A387E, MTL (ArenaGfxBank+$1E64)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxNJ.bin	;$1A3B88, NJ (ArenaGfxBank+$216E)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxNYI.bin	;$1A3E92, NYI (ArenaGfxBank+$2478)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxNYR.bin	;$1A419C, NYR (ArenaGfxBank+$2782)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxOTW.bin	;$1A44A6, OTW (ArenaGfxBank+$2A8C)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxPHI.bin	;$1A47B0, PHI (ArenaGfxBank+$2D96)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxPIT.bin	;$1A4ABA, PIT (ArenaGfxBank+$30A0)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxQUE.bin	;$1A4DC4, QUE (ArenaGfxBank+$33AA)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxSJ.bin	;$1A50CE, SJ (ArenaGfxBank+$36B4)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxSTL.bin	;$1A53D8, STL (ArenaGfxBank+$39BE)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxTB.bin	;$1A56E2, TB (ArenaGfxBank+$3CC8)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxTOR.bin	;$1A59EC, TOR (ArenaGfxBank+$3FD2)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxVAN.bin	;$1A5CF6, VAN (ArenaGfxBank+$42DC)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxWSH.bin	;$1A6000, WSH (ArenaGfxBank+$45E6)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxWPG.bin	;$1A630A, WPG (ArenaGfxBank+$48F0)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxBOS.bin	;$1A6614, BOS (ArenaGfxBank+$4BFA)
	incbin	..\Extracted\NHL95\Graphics\ArenaGfx\ArenaGfxASEASW.bin	;$1A691E, ASE / ASW (ArenaGfxBank+$4F04)
